# Generated by Django 2.0.13 on 2019-05-18 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='render.Subject'),
        ),
        migrations.AddField(
            model_name='snap',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='render.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='n',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
