# Generated by Django 2.0.13 on 2019-05-18 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_auto_20190518_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='n',
        ),
    ]
